server.port: 8081
fortune.service.uri: http://localhost:8080/
management:
  info.git.mode: full
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    config:
      enabled: false
