management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full
spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
